# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    # If errors occur, make sure configuration file is encoded as UTF-8
    unit_of_measurement: "°F"
    value_template: "{{ value | multiply(0.001) | round(1) }}"
  - platform: template
    sensors:
      cpu_usage:
        friendly_name: "CPU Usage"
        unit_of_measurement: "%"
        value_template: '{{ state_attr("sensor.glances_server_cpu", "total") }}'
  - platform: template
    sensors:
      memory_usage_mb:
        friendly_name: "Memory Usage"
        unit_of_measurement: "MB"
        value_template: '{{ (state_attr("sensor.glances_server_ram", "used") | float / 1024/1024) | round(0) }}'        

# Light Groups
light:
  - platform: group
    name: all_lights
    entities:
      - light.office_lamp
      - light.office_ceiling
      - light.bedroom_light
  - platform: group
    name: office_lights_group
    unique_id: office_lights_group 
    entities:
      - light.office_lamp
      - light.office_ceiling
  - platform: group
    name: bedroom_lights_group
    entities:
      - light.bedroom_light 

  # Translate switches to lights
  - platform: switch
    name: Bedroom Light
    entity_id: switch.bedroom_light

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
      type: module