title: Home
button_card_templates:
  !include /config/templates/template-index.yaml
views:
  - !include /config/views/overview.yaml
  - !include /config/views/office.yaml
  - !include /config/views/bedroom.yaml
