title: Home
views:
  - path: default_view
    title: Home
    badges:
      - entity: person.keagan
    cards:
      - type: light
        entity: light.office_lamp
      - type: light
        entity: light.porch
      - type: entities
        entities:
          - sensor.hp_envy_4520_series_black_ink
          - sensor.hp_envy_4520_series_tri_color_ink
          - sensor.hp_envy_4520_series
        title: Library
      - type: entities
        entities:
          - person.keagan
      - type: entities
        entities:
          - binary_sensor.rpi_power_status
          - binary_sensor.updater
        title: Binary sensor
      - type: entities
        entities:
          - entity: sensor.plex_keagan_s_desktop_v2
      - type: custom:button-card
        entity: light.office_lamp
        icon: mdi:chair-rolling
        custom_fields:
          abc:
            card:
              full_row: true
              hide_state: false
              type: custom:button-card
              entity: light.office_2
          slider:
            card:
              full_row: true
              hide_state: false
              type: custom:slider-entity-row
              entity: light.office_lamp
        color: rgb(28, 128, 199)
        tap_action:
          action: more-info
  - title: Office
    path: office
    badges: []
    cards:
      - entity: light.office_lamp
        name: Office Lights
        type: custom:button-card
        aspect_ratio: 4/1
        custom_fields:
          slider:
            card:
              entity: light.office_lamp
              full_row: true
              togle: false
              type: custom:slider-entity-row
